name: Build CODAL

on:
  workflow_dispatch:
  push:
    branches: 'master'

jobs:
  build-py-script:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build.py ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain (Ubuntu)
        if: runner.os == 'Linux'
        run: sh ./.github/workflows/scripts/install-toolchain-ubuntu.sh
      - name: Install toolchain (Windows)
        if: runner.os == 'Windows'
        run: .\.github\workflows\scripts\install-toolchain-win.ps1
      - name: Install toolchain (macOS)
        if: runner.os == 'macOS'
        run: sh ./.github/workflows/scripts/install-toolchain-mac.sh
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          ninja --version
      - name: Build using build.py
        run: python build.py
      - name: Upload hex file
        uses: actions/upload-artifact@v1
        with:
          name: build-py-${{ matrix.os }}
          path: MICROBIT.hex
