name: Build CODAL

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    # Runs every working day at 8 am
    - cron: '0 8 * * 1-5'

jobs:
  build-py-script:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2016]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build.py ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup arm-none-eabi-gcc
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '10-2020-q4'
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.20'
      - name: Install Ninja via PyPI
        run: python -m pip install ninja
      - name: Check Versions
        run: |
          arm-none-eabi-gcc --version
          cmake --version
          ninja --version
          python --version
      - name: Build using build.py
        run: python build.py
      - name: Upload hex file
        uses: actions/upload-artifact@v1
        with:
          name: build-py-${{ matrix.os }}
          path: MICROBIT.hex
